# Example render.yaml file

# Define a web service
services:
  - type: web
    name: my-web-service
    env: node
    repo: https://github.com/gojam13/gojam13
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

# Define a database
databases:
  - name: my-database
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all IPs

# Define environment variables
envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: my-database
      property: connectionString
  - key: SECRET_KEY
    generateValue: true
